import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import Sidebar from "@/components/ui/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="w-full h-full m-0 p-0">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full m-0 p-0`}>
        <div className="flex w-screen h-screen m-0 p-0">
          <Sidebar />
          <div className="flex-1 w-full h-full bg-transparent m-0 p-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
